export const matchesData = [
  { title: "Accounting & Financial", count: 418 },
  { title: "Admin & Project Management", count: 511 },
  { title: "Audio & Video", count: 292 },
  { title: "Consulting & Business Strategy", count: 337 },
  { title: "Customer Service & Sales", count: 285 },
  { title: "Data & Analytics", count: 328 },
  { title: "Design", count: 1089 },
  { title: "Engineering & Architecture", count: 149 },
  { title: "IT, Network, & Software Implementation", count: 264 },
  { title: "Legal", count: 53 },
  { title: "Marketing & Branding", count: 735 },
  { title: "Software, Mobile, & Web Dev", count: 539 },
  { title: "Translation", count: 335 },
  { title: "Writing & Editing", count: 949 },
];
