export interface CountryDatas {
    id: string;
    name: string;
    states: string[];
  }
  
  export const countryStatess: CountryDatas[] = [
    {
      id: "US",
      name: "United States",
      states: [
        "Alabama",
        "Alaska",
        "Arizona",
        "Arkansas",
        "California",
        "Colorado",
        "Connecticut",
        "Delaware",
        "Florida",
        "Georgia",
        "Hawaii",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Kansas",
        "Kentucky",
        "Louisiana",
        "Maine",
        "Maryland",
        "Massachusetts",
        "Michigan",
        "Minnesota",
        "Mississippi",
        "Missouri",
        "Montana",
        "Nebraska",
        "Nevada",
        "New Hampshire",
        "New Jersey",
        "New Mexico",
        "New York",
        "North Carolina",
        "North Dakota",
        "Ohio",
        "Oklahoma",
        "Oregon",
        "Pennsylvania",
        "Rhode Island",
        "South Carolina",
        "South Dakota",
        "Tennessee",
        "Texas",
        "Utah",
        "Vermont",
        "Virginia",
        "Washington",
        "West Virginia",
        "Wisconsin",
        "Wyoming",
      ],
    },
    {
      id: "IL",
      name: "Israel",
      states: [
        "Central District",
        "Haifa District",
        "Jerusalem District",
        "Northern District",
        "Southern District",
        "Tel Aviv District",
      ],
    },
    {
      id: "UK",
      name: "United Kingdom",
      states: ["England", "Scotland", "Wales", "Northern Ireland"],
    },
    {
      id: "BE",
      name: "Belgium",
      states: ["Flemish Region", "Walloon Region", "Brussels-Capital Region"],
    },
    {
      id: "CA",
      name: "Canada",
      states: [
        "Alberta",
        "British Columbia",
        "Manitoba",
        "New Brunswick",
        "Newfoundland and Labrador",
        "Nova Scotia",
        "Ontario",
        "Prince Edward Island",
        "Quebec",
        "Saskatchewan",
        "Northwest Territories",
        "Nunavut",
        "Yukon",
      ],
    },
    {
      id: "ZA",
      name: "South Africa",
      states: [
        "Eastern Cape",
        "Free State",
        "Gauteng",
        "KwaZulu-Natal",
        "Limpopo",
        "Mpumalanga",
        "Northern Cape",
        "North West",
        "Western Cape",
      ],
    },
    {
      id: "AU",
      name: "Australia",
      states: [
        "New South Wales",
        "Queensland",
        "South Australia",
        "Tasmania",
        "Victoria",
        "Western Australia",
        "Australian Capital Territory",
        "Northern Territory",
      ],
    },
    {
      id: "MX",
      name: "Mexico",
      states: [
        "Aguascalientes",
        "Baja California",
        "Baja California Sur",
        "Campeche",
        "Chiapas",
        "Chihuahua",
        "Coahuila",
        "Colima",
        "Durango",
        "Guanajuato",
        "Guerrero",
        "Hidalgo",
        "Jalisco",
        "Mexico State",
        "Michoacán",
        "Morelos",
        "Nayarit",
        "Nuevo León",
        "Oaxaca",
        "Puebla",
        "Querétaro",
        "Quintana Roo",
        "San Luis Potosí",
        "Sinaloa",
        "Sonora",
        "Tabasco",
        "Tamaulipas",
        "Tlaxcala",
        "Veracruz",
        "Yucatán",
        "Zacatecas",
      ],
    },
    {
      id: "FR",
      name: "France",
      states: [
        "Auvergne-Rhône-Alpes",
        "Bourgogne-Franche-Comté",
        "Brittany",
        "Centre-Val de Loire",
        "Corsica",
        "Grand Est",
        "Hauts-de-France",
        "Île-de-France",
        "Normandy",
        "Nouvelle-Aquitaine",
        "Occitanie",
        "Pays de la Loire",
        "Provence-Alpes-Côte d'Azur",
      ],
    },
    {
      id: "DE",
      name: "Germany",
      states: [
        "Baden-Württemberg",
        "Bavaria",
        "Berlin",
        "Brandenburg",
        "Bremen",
        "Hamburg",
        "Hesse",
        "Lower Saxony",
        "Mecklenburg-Vorpommern",
        "North Rhine-Westphalia",
        "Rhineland-Palatinate",
        "Saarland",
        "Saxony",
        "Saxony-Anhalt",
        "Schleswig-Holstein",
        "Thuringia",
      ],
    },
    {
      id: "AR",
      name: "Argentina",
      states: ["Buenos Aires", "Córdoba", "Santa Fe", "Mendoza", "Tucumán"],
    },
    {
      id: "BR",
      name: "Brazil",
      states: [
        "São Paulo",
        "Rio de Janeiro",
        "Minas Gerais",
        "Bahia",
        "Rio Grande do Sul",
      ],
    },
    {
      id: "HU",
      name: "Hungary",
      states: ["Central Hungary", "Transdanubia", "Great Plain"],
    },
    {
      id: "CH",
      name: "Switzerland",
      states: ["Zürich", "Geneva", "Vaud", "Bern", "Lucerne"],
    },
    {
      id: "PA",
      name: "Panama",
      states: ["Panamá", "Chiriquí", "Bocas del Toro", "Coclé", "Colón"],
    },
    {
      id: "NZ",
      name: "New Zealand",
      states: ["Auckland", "Wellington", "Canterbury", "Otago", "Waikato"],
    },
    {
      id: "GI",
      name: "Gibraltar",
      states: [],
    },
    {
      id: "AT",
      name: "Austria",
      states: ["Vienna", "Tyrol", "Salzburg", "Carinthia", "Upper Austria"],
    },
  ];
  